
modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="recipe_enhancements" #mandatory
version="1.16.5-1.5.0" #mandatory
displayName="Recipe Enhancements" #mandatory
logoFile="recipe_enhancements.png" #optional
authors="ISenseHostility" #optional
description='''
Recipe Enhancements aims to make Minecraft recipes just a little bit better and expansive, without interfering with the vanilla feel of the recipes!
'''
